local spell = Spell("instant")
function spell.onCastSpell(creature, var)
    local condition = Condition(CONDITION_ATTRIBUTES)
    condition:setParameter(CONDITION_PARAM_SUBID, 4)
    condition:setParameter(CONDITION_PARAM_BUFF, true)
    condition:setParameter(CONDITION_PARAM_TICKS, 2 * 60 * 1000)
    condition:setParameter(CONDITION_PARAM_STAT_MAXMANAPERCENT, 110)
    creature:addCondition(condition)
    creature:getPosition():sendMagicEffect(CONST_ME_MAGIC_RED)
    return true
end

spell:group("support")
spell:id(568)
spell:name("Utamo Strong")
spell:words("utamo strong")
spell:level(14)
spell:mana(50)
spell:isSelfTarget(true)
spell:isPremium(true)
spell:isAggressive(false)
spell:cooldown(2 * 1000)
spell:groupCooldown(2 * 1000)
spell:needLearn(false)
spell:vocation("sorcerer;true", "master sorcerer;true", "druid;true", "elder druid;true", "paladin;true", "royal paladin;true")
spell:register()
